language: python
install: pip install jsonschema pytest
script:
- py.test -vv
- python validate.py
- php validate.php
deploy:
  provider: npm
  email: martin.monperrus@gnieh.org
  api_key:
    secure: YgdBbKjxy+DRdQcItgiwq3gMjxzFbZsplv13Lb5Ewzb+n6CO7U/RHEdLMHRfE/3xlQIaMMvbjjBSBUR9rDpMqClrfnkwf2RtXKQGImQ9Z8vvRKIWEn1UDoFLPtRtVrPU/7K96LbJsSyncM8HDEsF3s22WdiDcFhuH3/PjWxxr5g=
  on:
    repo: monperrus/crawler-user-agents
    branch: master
